export const personalData = [
  { nro: 1, grado: "CY Int", especialidad: "OF", apellidoNombre: "LOPEZ BUENO, Pablo Gabriel", unidad: "Dir Int", cargo: "Direccion" },
  { nro: 2, grado: "CR Int", especialidad: "OF", apellidoNombre: "MONTIVERO, Roberto Enrique", unidad: "Dir Int", cargo: "Direccion" },
  { nro: 3, grado: "CR Int", especialidad: "OF", apellidoNombre: "VILLANI MORALES, José María", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 4, grado: "CR Int", especialidad: "OF", apellidoNombre: "DÁSCOLA, Fabián Alejandro", unidad: "Sas Mil Cen", cargo: "Jefatura" },
  { nro: 5, grado: "TC Int", especialidad: "OF", apellidoNombre: "D'ANGELO, Daniel Ruben", unidad: "Dir Int", cargo: "Dpto Insp" },
  { nro: 6, grado: "TC Int", especialidad: "OF", apellidoNombre: "BLANCO, Enrique Miguel", unidad: "B Int 601", cargo: "Jefatura" },
  { nro: 7, grado: "TC Int", especialidad: "OF", apellidoNombre: "QUINTANA, Ángel Daniel", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 8, grado: "TC Int", especialidad: "OF", apellidoNombre: "DELGADO, Cristian Manuel", unidad: "Dir Int", cargo: "Dpto Insp" },
  { nro: 9, grado: "TC Int", especialidad: "OF", apellidoNombre: "FERREYRA, Gustavo Fernando", unidad: "Sas Mil Cen", cargo: "Jefatura" },
  { nro: 10, grado: "TC Int", especialidad: "OF", apellidoNombre: "LOPEZ, Ariel Gustavo", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 11, grado: "MY Int", especialidad: "OF", apellidoNombre: "GUZMAN, Gustavo Augusto", unidad: "Dir Int", cargo: "Dpto Adq" },
  { nro: 12, grado: "MY Bda", especialidad: "OF", apellidoNombre: "COUTINHO, Daniel German", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 13, grado: "MY Int", especialidad: "OF", apellidoNombre: "OHORMAECHE, Pedro Gustavo", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 14, grado: "MY Int", especialidad: "OF", apellidoNombre: "CHAVES, José Leonardo", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 15, grado: "MY Med", especialidad: "OF", apellidoNombre: "GARRASTAZUL, Patricia Eliana", unidad: "Dir Int", cargo: "San" },
  { nro: 16, grado: "MY Int", especialidad: "OF", apellidoNombre: "QUIROGA, Luis Mariano Egidio", unidad: "B Int 601", cargo: "Jefatura" },
  { nro: 17, grado: "MY Int", especialidad: "OF", apellidoNombre: "SZKROMYDA, Fanny Yanel", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 18, grado: "MY Int", especialidad: "OF", apellidoNombre: "RODRIGUEZ, Cintia Melisa", unidad: "B Int 601", cargo: "Operaciones" },
  { nro: 19, grado: "MY Aud", especialidad: "OF", apellidoNombre: "SUAREZ, Pablo Sebastián", unidad: "Sas Mil Cen", cargo: "Jurídica" },
  { nro: 20, grado: "MY Int", especialidad: "OF", apellidoNombre: "LEIVA, Facundo Emanuel", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 21, grado: "CT Bda", especialidad: "OF", apellidoNombre: "NEWBERRY, Arnoldo Natalio", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 22, grado: "CT A", especialidad: "OF", apellidoNombre: "ROMERO ACOSTA, Daniel Alejandro", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 23, grado: "CT Aud", especialidad: "OF", apellidoNombre: "BARRERA DIAZ, Giselle Alejandra", unidad: "Dir Int", cargo: "Dpto Jur" },
  { nro: 24, grado: "CT Int", especialidad: "OF", apellidoNombre: "GARINO, Jennifer Lis", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 25, grado: "CT Int", especialidad: "OF", apellidoNombre: "LUCA, Emiliano Miguel", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 26, grado: "CT Aud", especialidad: "OF", apellidoNombre: "RODRIGUEZ, Natalia Denisse", unidad: "Dir Int", cargo: "Dpto Jur" },
  { nro: 27, grado: "CT Int", especialidad: "OF", apellidoNombre: "MARQUEZ, Rogelio Nestor", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 28, grado: "CT Int", especialidad: "OF", apellidoNombre: "SANCHEZ ALBORNOZ, Santiago", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 29, grado: "CT Int", especialidad: "OF", apellidoNombre: "ABALOS, Cesar Emanuel", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 30, grado: "CT Int", especialidad: "OF", apellidoNombre: "MONGES TREVIÑO, Facundo", unidad: "B Int 601", cargo: "COL" },
  { nro: 31, grado: "CT Int", especialidad: "OF", apellidoNombre: "ROJAS, Manuel Guillermo", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 32, grado: "CT Int", especialidad: "OF", apellidoNombre: "AIBA, Milciades De Jesus", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 33, grado: "CT Int", especialidad: "OF", apellidoNombre: "ESPINOSA, Doris Edith", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 34, grado: "TP Int", especialidad: "OF", apellidoNombre: "RODRIGUEZ, Daniel Eduardo", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 35, grado: "TP Int", especialidad: "OF", apellidoNombre: "CAUCOTA, Dardo Antony Milagro", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 36, grado: "TP Int", especialidad: "OF", apellidoNombre: "CHINCHILLA, Ruben Amado", unidad: "Sas Mil Cen", cargo: "CRE" },
  { nro: 37, grado: "TT Bda", especialidad: "OF", apellidoNombre: "SUAREZ, Diego Orlando", unidad: "B Int 601", cargo: "Taller Bda" },
  { nro: 38, grado: "TT Int", especialidad: "OF", apellidoNombre: "AGUIRRE, Ariana Marisol", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 39, grado: "TT Int", especialidad: "OF", apellidoNombre: "CALLEJO, Florencia Rocio", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 40, grado: "TT Int", especialidad: "OF", apellidoNombre: "MARIANI, Javier Alberto", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 41, grado: "TT Ars", especialidad: "OF", apellidoNombre: "RIVAS, Jonathan Emmanuel", unidad: "B Int 601", cargo: "Cdo Ser" },
  { nro: 42, grado: "TT Educ Fis", especialidad: "OF", apellidoNombre: "SANTILLAN CHARY, Juan Jose", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 43, grado: "TT Int", especialidad: "OF", apellidoNombre: "GIMENEZ, Alexia Mailen", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 44, grado: "TT Int", especialidad: "OF", apellidoNombre: "COLMAN OLIVERIO, Carlos Nahuel", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 45, grado: "TT SCD Reclut Loc", especialidad: "OF", apellidoNombre: "RUIZ FRANCES, Ariana Estefanis", unidad: "Dir Int", cargo: "Div Com Info" },
  { nro: 46, grado: "SM Int", especialidad: "SB", apellidoNombre: "BRAHIM, Diego Alejandro", unidad: "Dir Int", cargo: "ENC ELEM" },
  { nro: 47, grado: "SM Int", especialidad: "SB", apellidoNombre: "SOSA, Felix Isabelino", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 48, grado: "SM Sas", especialidad: "SB", apellidoNombre: "SARCEDA, Jorge Mario", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 49, grado: "SM Coc", especialidad: "SB", apellidoNombre: "BRITOS, Pablo Raul", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 50, grado: "SM Mus", especialidad: "SB", apellidoNombre: "QUINTANA, Antonio Agustin", unidad: "B Int 601", cargo: "Taller Bda" },
  { nro: 51, grado: "SM  Mus", especialidad: "SB", apellidoNombre: "AGUILAR, Daniel Alejandro", unidad: "B Int 601", cargo: "Taller Bda" },
  { nro: 52, grado: "SP Int", especialidad: "SB", apellidoNombre: "VILLALBA, Daniel", unidad: "B Int 601", cargo: "ENC ELEM" },
  { nro: 53, grado: "SP Zap", especialidad: "SB", apellidoNombre: "ALBORNOZ, Luis Alberto Isidoro", unidad: "Dir Int", cargo: "Dpto Insp" },
  { nro: 54, grado: "SP Sas", especialidad: "SB", apellidoNombre: "AGUILAR, Paulina", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 55, grado: "SP Sas", especialidad: "SB", apellidoNombre: "TRONCOSO, Mirta Beba", unidad: "Sas Mil Cen", cargo: "ENC ELEM" },
  { nro: 56, grado: "SP Sas", especialidad: "SB", apellidoNombre: "GONZALEZ, Ariel Marcelo", unidad: "Sas Mil Cen EC Sas Mil Suc CÓRDOBA", cargo: "DPTO COMER" },
  { nro: 57, grado: "SP (F) Int", especialidad: "SB", apellidoNombre: "ABALOS, Fernando Gabriel", unidad: "B Int 601", cargo: "Cas Subof" },
  { nro: 58, grado: "SP (D) Coc", especialidad: "SB", apellidoNombre: "ALBORNOZ, Alejandro Marcelo", unidad: "Trámite de Retiro", cargo: "RETIRO" },
  { nro: 59, grado: "SP Coc", especialidad: "SB", apellidoNombre: "TORRES, Gerardo Luciano", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 60, grado: "SP Coc", especialidad: "SB", apellidoNombre: "DIAZ, Octavio Melchor", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 61, grado: "SP Coc", especialidad: "SB", apellidoNombre: "SREBERNICHE, Nelson Adrián", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 62, grado: "SA Mus", especialidad: "SB", apellidoNombre: "RICAVET, Martín Leonardo", unidad: "Dir Int", cargo: "Dpto Insp" },
  { nro: 63, grado: "SA Int", especialidad: "SB", apellidoNombre: "BRITOS, Carlos Alberto", unidad: "Sas Mil Cen", cargo: "DIV CEN" },
  { nro: 64, grado: "SA Enf Grl", especialidad: "SB", apellidoNombre: "ESPINOZA, Graciela Santusa", unidad: "Dir Int", cargo: "San" },
  { nro: 65, grado: "SA Mec Info", especialidad: "SB", apellidoNombre: "MAITA, Héctor Sebastián", unidad: "B Int 601", cargo: "COL" },
  { nro: 66, grado: "SA Sas", especialidad: "SB", apellidoNombre: "HERRERA, Diego Maximiliano", unidad: "B Int 601", cargo: "Cdo Ser" },
  { nro: 67, grado: "SA Ofic", especialidad: "SB", apellidoNombre: "RODRIGUEZ, Cintia Natalia", unidad: "Dir Int", cargo: "Direccion" },
  { nro: 68, grado: "SA Ofic", especialidad: "SB", apellidoNombre: "LOPEZ, Daniela Claudia", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 69, grado: "SA Conduc Mot", especialidad: "SB", apellidoNombre: "PEREZ, Germán Leonardo", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 70, grado: "SA  Int", especialidad: "SB", apellidoNombre: "HUANCO, Marcelo Andrés", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 71, grado: "SA Int", especialidad: "SB", apellidoNombre: "LOPEZ, Daniel Christian", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 72, grado: "SA Sas", especialidad: "SB", apellidoNombre: "PEDRAZA, Mirta Azucena", unidad: "Sas Mil Cen EC Sas Mil Suc CÓRDOBA", cargo: "DPTO COMER" },
  { nro: 73, grado: "SA (D) Coc(c)", especialidad: "SB", apellidoNombre: "COPA, Jorge Humberto", unidad: "B Int 601", cargo: "Tramite de baja" },
  { nro: 74, grado: "SA (D) Int(c)", especialidad: "SB", apellidoNombre: "WEIMAN, Diego Roque", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 75, grado: "SI Conduc Mot", especialidad: "SB", apellidoNombre: "BACHMANN, Darío Edgardo", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 76, grado: "SI Int", especialidad: "SB", apellidoNombre: "REYNALDO LEMES, Paul", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 77, grado: "SI Int", especialidad: "SB", apellidoNombre: "GONZALEZ YARLEQUE, Valeria", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 78, grado: "SI Sas", especialidad: "SB", apellidoNombre: "GALLARDO, Sergio Fabián", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 79, grado: "SI Zap", especialidad: "SB", apellidoNombre: "SOSA, Cristian Leandro", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 80, grado: "SI Conduc Mot", especialidad: "SB", apellidoNombre: "RODRIGUEZ, Leonardo Javier", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 81, grado: "SI Sas", especialidad: "SB", apellidoNombre: "ZENTENO, Marisa Paola Leonor", unidad: "Sas Mil Cen EC Sas Mil Suc MENDOZA", cargo: "DPTO COMER" },
  { nro: 82, grado: "SI Zap", especialidad: "SB", apellidoNombre: "OJEDA, Laura Carolina", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 83, grado: "SI Zap", especialidad: "SB", apellidoNombre: "FRAILE, Juan Marcelo", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 84, grado: "SI Conduc Mot", especialidad: "SB", apellidoNombre: "HOLZWEISSIG, Daniel Alejandro", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 85, grado: "SI Int", especialidad: "SB", apellidoNombre: "GOMEZ, Lucio Oscar", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 86, grado: "SI Sas", especialidad: "SB", apellidoNombre: "ZUBELZA, Adriana Evangelina", unidad: "Sas Mil Cen", cargo: "Dpto Prod" },
  { nro: 87, grado: "SI Zap", especialidad: "SB", apellidoNombre: "CORIA, Adán", unidad: "B Int 601", cargo: "Sec Ars" },
  { nro: 88, grado: "SI Ing", especialidad: "SB", apellidoNombre: "GONZALEZ, Matías Emanuel", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 89, grado: "SI  Int", especialidad: "SB", apellidoNombre: "HIRSCHFELD, Jorge Adrián", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 90, grado: "SI Sas", especialidad: "SB", apellidoNombre: "SUÁREZ, Ingrid Bárbara", unidad: "Sas Mil Cen", cargo: "DIV CEN" },
  { nro: 91, grado: "SI Coc", especialidad: "SB", apellidoNombre: "TABORDA, Nélida Johana", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 92, grado: "SI Sas", especialidad: "SB", apellidoNombre: "CABRAL, Noemí Aída", unidad: "Sas Mil Cen", cargo: "DIV CEN" },
  { nro: 93, grado: "SI  Zap", especialidad: "SB", apellidoNombre: "ROA, Ricardo Abel", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 94, grado: "SI  Zap", especialidad: "SB", apellidoNombre: "ANTUNEZ, Sebastián Ariel", unidad: "B Int 601", cargo: "Cas Subof" },
  { nro: 95, grado: "SI Coc", especialidad: "SB", apellidoNombre: "COLMAN, Yesenia Iris", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 96, grado: "SI Ofic", especialidad: "SB", apellidoNombre: "LOPEZ, Viviana Mariana Beatriz", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 97, grado: "SI (D) Mus(c)", especialidad: "SB", apellidoNombre: "FARFAN, Héctor Alejandro", unidad: "B Int 601", cargo: "Taller Bda" },
  { nro: 98, grado: "SG  Ofic", especialidad: "SB", apellidoNombre: "LUENGO, Carla Daniela", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 99, grado: "SG Ofic", especialidad: "SB", apellidoNombre: "BESSÓN MENGEN, Marco Antonio", unidad: "Dir Int", cargo: "Direccion" },
  { nro: 100, grado: "SG Enf Grl", especialidad: "SB", apellidoNombre: "GUERRERO, Delina Hilda", unidad: "Dir Int", cargo: "San" },
  { nro: 101, grado: "SG Mus", especialidad: "SB", apellidoNombre: "TORRES, Marcos Javier", unidad: "B Int 601", cargo: "Taller Bda" },
  { nro: 102, grado: "SG Sas", especialidad: "SB", apellidoNombre: "MISURELLI, Mariano Joaquín", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 103, grado: "SG I", especialidad: "SB", apellidoNombre: "VARGAS, Sergio Roberto", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 104, grado: "SG Conduc Mot", especialidad: "SB", apellidoNombre: "DONAIRE, Jonathan Ariel", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 105, grado: "SG  Int", especialidad: "SB", apellidoNombre: "QUIPILDOR, Verónica Elisabeth", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 106, grado: "SG  Mec Inst", especialidad: "SB", apellidoNombre: "CENTURIÓN, Ariel Alejandro", unidad: "B Int 601", cargo: "Cas Of" },
  { nro: 107, grado: "SG  Mus", especialidad: "SB", apellidoNombre: "PEÑA, Néstor Alejandro", unidad: "B Int 601", cargo: "Taller Bda" },
  { nro: 108, grado: "SG Sas", especialidad: "SB", apellidoNombre: "ALMIRÓN, Johanna Melisa", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 109, grado: "SG  Conduc Mot", especialidad: "SB", apellidoNombre: "ESCALANTE LEGAL, Cristian", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 110, grado: "SG Conduc Mot", especialidad: "SB", apellidoNombre: "TOLAY, Irenia Margarita", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 111, grado: "SG Int", especialidad: "SB", apellidoNombre: "BRUNO, Leonardo Antonio", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 112, grado: "SG Int", especialidad: "SB", apellidoNombre: "SANTUCHO, Carlos Alejandro", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 113, grado: "SG Int", especialidad: "SB", apellidoNombre: "GUTIERREZ, Estela Maris", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 114, grado: "SG Mec Info", especialidad: "SB", apellidoNombre: "FLORES, Yesica Leandra", unidad: "Dir Int", cargo: "Div Com Info" },
  { nro: 115, grado: "SG Cama", especialidad: "SB", apellidoNombre: "ORTEGA, Sebastián Emmanuel", unidad: "Dir Int", cargo: "Direccion" },
  { nro: 116, grado: "SG Zap", especialidad: "SB", apellidoNombre: "ESPINDOLA, Cristian Raul", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 117, grado: "SG Zap", especialidad: "SB", apellidoNombre: "CZYPUSAK MARAINS, José", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 118, grado: "SG Conduc Mot", especialidad: "SB", apellidoNombre: "BERON GOMEZ, Naira Maribel", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 119, grado: "SG Mec Eq Camp", especialidad: "SB", apellidoNombre: "CENARDO, Luciano Emanuel", unidad: "Dir Int", cargo: "Div Com Info" },
  { nro: 120, grado: "SG Cama", especialidad: "SB", apellidoNombre: "GUZMAN, Jaquelina de Ángeles", unidad: "B Int 601", cargo: "Jefatura" },
  { nro: 121, grado: "SG Ofic", especialidad: "SB", apellidoNombre: "PANGUILEF, Verónica Noelia", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 122, grado: "SG Conduc Mot", especialidad: "SB", apellidoNombre: "CONDORI, Tamara Antonela del Carmen", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 123, grado: "SG  Conduc Mot", especialidad: "SB", apellidoNombre: "DEPSAL, Analía Veronica", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 124, grado: "SG  Int", especialidad: "SB", apellidoNombre: "ORTIZ, Rocio Elizabeth", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 125, grado: "SG Mec Eq Fij", especialidad: "SB", apellidoNombre: "CAMINO, Zulma Alejandra", unidad: "Dir Int", cargo: "Div Com Info" },
  { nro: 126, grado: "SG Zap", especialidad: "SB", apellidoNombre: "COLMAN, Leonardo Javier", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 127, grado: "SG Mec Mot Rueda", especialidad: "SB", apellidoNombre: "OSMAN, Ignacio Nazareno", unidad: "B Int 601", cargo: "Sec Ars" },
  { nro: 128, grado: "CI Conduc Mot", especialidad: "SB", apellidoNombre: "VALFRE, Luís Iván", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 129, grado: "CI Int", especialidad: "SB", apellidoNombre: "ROJAS, Gabriela Fernanda", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 130, grado: "CI Int", especialidad: "SB", apellidoNombre: "GUILLEN, Josefina", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 131, grado: "CI Int", especialidad: "SB", apellidoNombre: "ALARCON, Brenda Antonella", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 132, grado: "CI EC Conduc Mot", especialidad: "SB", apellidoNombre: "FERREYRA, Mauricio Fabián", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 133, grado: "CI Int", especialidad: "SB", apellidoNombre: "SALGUEIRO, Miguel Alejandro", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 134, grado: "CI Art 11 Conduc Mot", especialidad: "SB", apellidoNombre: "SCIFO, Luciano Martín", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 135, grado: "CI Art 11 Zap", especialidad: "SB", apellidoNombre: "RIVERO, Sergio Emanuel", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 136, grado: "CI Int", especialidad: "SB", apellidoNombre: "CONDORI, Julieta Erica de los Ángeles", unidad: "Dir Int", cargo: "Dpto Adq" },
  { nro: 137, grado: "CI Sas", especialidad: "SB", apellidoNombre: "ALTAMIRANO, José Luis", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 138, grado: "CI Sas", especialidad: "SB", apellidoNombre: "CACERES, Héctor Fabián", unidad: "Sas Mil Cen MZA", cargo: "DPTO COMER" },
  { nro: 139, grado: "CI Sas", especialidad: "SB", apellidoNombre: "PRIETO, Jenifer Tamara", unidad: "Dir Int", cargo: "Dpto Insp" },
  { nro: 140, grado: "CI Int", especialidad: "SB", apellidoNombre: "FLORES, Adriana Paola", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 141, grado: "CI Int", especialidad: "SB", apellidoNombre: "LAYME ROJAS, Ricardo Daniel", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 142, grado: "CI Int", especialidad: "SB", apellidoNombre: "AGUILERA, Nancy Mabel", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 143, grado: "CI Int", especialidad: "SB", apellidoNombre: "LEÓN, Milena Maria", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 144, grado: "CI Int", especialidad: "SB", apellidoNombre: "PAVON, Emilio Isaias", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 145, grado: "CI Sas", especialidad: "SB", apellidoNombre: "FERNANDEZ, Jessica Soledad", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 146, grado: "CI Sas", especialidad: "SB", apellidoNombre: "REPETTO, Lourdes Anahi", unidad: "Sas Mil Cen", cargo: "Dpto Prod" },
  { nro: 147, grado: "CI Sas", especialidad: "SB", apellidoNombre: "MAIDANA, Rocio Ayelen", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 148, grado: "CI Sas", especialidad: "SB", apellidoNombre: "ALVARRACIN, Axel Fernando", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 149, grado: "CI Ofic", especialidad: "SB", apellidoNombre: "LEZCANO, Amelia Soledad", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 150, grado: "CI EC Sas", especialidad: "SB", apellidoNombre: "PINTO, Mirta Angélica", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 151, grado: "CI Art 11 Coc", especialidad: "SB", apellidoNombre: "CORDOBA, Hugo Cesar", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 152, grado: "CI Int", especialidad: "SB", apellidoNombre: "CAMACHO MONTERO, Analia Soledad", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 153, grado: "CI Int", especialidad: "SB", apellidoNombre: "VILCA, Fernando Ezequiel", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 154, grado: "CI Int", especialidad: "SB", apellidoNombre: "GREGORIO, Matias Javier", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 155, grado: "CI Mus", especialidad: "SB", apellidoNombre: "CASTILLO, Gaston Armando", unidad: "B Int 601", cargo: "Taller Bda" },
  { nro: 156, grado: "CI  Sas", especialidad: "SB", apellidoNombre: "ARIAS, Lorena Hilda", unidad: "Sas Mil Cen", cargo: "Suc Azopardo" },
  { nro: 157, grado: "CI Art 11 (F) Coc", especialidad: "SB", apellidoNombre: "LEZCANO, Guillermo Agustín", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 158, grado: "CB Conduc Mot", especialidad: "SB", apellidoNombre: "MAIDANA, Ayrton Leonel", unidad: "Dir Int", cargo: "Parque Autom" },
  { nro: 159, grado: "CB Int", especialidad: "SB", apellidoNombre: "GONZALEZ, Yamila Nadin", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 160, grado: "CB Sas", especialidad: "SB", apellidoNombre: "BAEZ, Luis Hernan", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 161, grado: "CB Sas", especialidad: "SB", apellidoNombre: "VALENCIA, Florencia Maria Jesus", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 162, grado: "CB Sas", especialidad: "SB", apellidoNombre: "LOPEZ, Cledia Mabel", unidad: "Sas Mil Cen", cargo: "CRE" },
  { nro: 163, grado: "CB Sas", especialidad: "SB", apellidoNombre: "MARTINEZ, Florencia Abigail", unidad: "Sas Mil Cen", cargo: "Dpto Prod" },
  { nro: 164, grado: "CB Sas", especialidad: "SB", apellidoNombre: "DIAZ, Rocio Florencia", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 165, grado: "CB Sas", especialidad: "SB", apellidoNombre: "LOPEZ, Natalia Rocio", unidad: "Sas Mil Cen", cargo: "Dpto Prod" },
  { nro: 166, grado: "CB Sas", especialidad: "SB", apellidoNombre: "RUIZ DIAZ, Franco Gabriel", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 167, grado: "CB Sas", especialidad: "SB", apellidoNombre: "OLMEDO, Franco Emanuel", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 168, grado: "CB Sas", especialidad: "SB", apellidoNombre: "GARNICA, Valeria Ayelen", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 169, grado: "CB Sas", especialidad: "SB", apellidoNombre: "SAUCEDO, Melina Aylen", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 170, grado: "CB Sas", especialidad: "SB", apellidoNombre: "PEÑA, Evelin Leonor Antonella", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 171, grado: "CB Sas", especialidad: "SB", apellidoNombre: "ZALAZAR, Melisa Andrea", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 172, grado: "CB Cama", especialidad: "SB", apellidoNombre: "MALDONADO, Brenda Belen", unidad: "Dir Int", cargo: "Direccion" },
  { nro: 173, grado: "CB Mec Inst", especialidad: "SB", apellidoNombre: "TARCAYA, Juaquin Horacio", unidad: "Dir Int", cargo: "Sec Destinos" },
  { nro: 174, grado: "CB  Zap", especialidad: "SB", apellidoNombre: "MAIDANA BARRETO, Mauricio Ismael", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 175, grado: "CB Art 11 Sas", especialidad: "SB", apellidoNombre: "FERNANDEZ, Luis Pablo", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 176, grado: "CB Art 11 Sas", especialidad: "SB", apellidoNombre: "QUINTONAHUEL, Ailén Emilce", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 177, grado: "CB Art 11 Sas", especialidad: "SB", apellidoNombre: "LOPEZ CHAMORRO, Martín Alejandro", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 178, grado: "CB Art 11 Coc", especialidad: "SB", apellidoNombre: "ANDRADE, Aaron Elias", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 179, grado: "CB Sas", especialidad: "SB", apellidoNombre: "VALLEJOS MEDINA, Marcos Agustin", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 180, grado: "CB Sas", especialidad: "SB", apellidoNombre: "MARTINEZ, Yamila Tatiana", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 181, grado: "CB Int", especialidad: "SB", apellidoNombre: "CHEVASCO, Gisela Yamila", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 182, grado: "CB Int", especialidad: "SB", apellidoNombre: "ALVAREZ, Matias Aaron", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 183, grado: "CB EC Sas", especialidad: "SB", apellidoNombre: "TORO, Alexis Jesus", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 184, grado: "CB EC Sas", especialidad: "SB", apellidoNombre: "FERNANDEZ, Joaquín Facundo", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 185, grado: "CB EC Sas", especialidad: "SB", apellidoNombre: "SILVEIRA, German Ricardo", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 186, grado: "CB EC Sas", especialidad: "SB", apellidoNombre: "AZOGARAY, Triana Jacqueline", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 187, grado: "CB EC Sas", especialidad: "SB", apellidoNombre: "PALMA, Malena Yazmin", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 188, grado: "CB EC Sas", especialidad: "SB", apellidoNombre: "MOYANO, Gisela Anahí", unidad: "Sas Mil Cen", cargo: "DIV CEN" },
  { nro: 189, grado: "CB EC Sas", especialidad: "SB", apellidoNombre: "TOLOZA, Brisa Alejandra", unidad: "Sas Mil Cen", cargo: "Dpto Prod" },
  { nro: 190, grado: "CB EC Coc", especialidad: "SB", apellidoNombre: "CRUZ, Mayra Leila", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 191, grado: "CB EC Coc", especialidad: "SB", apellidoNombre: "SOSA, Claudio Alejandro", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 192, grado: "CB EC Sas", especialidad: "SB", apellidoNombre: "PASTRANA, Ines Guadalupe", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 193, grado: "CB EC Zap", especialidad: "SB", apellidoNombre: "CARDOZO, Heber Oscar", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 194, grado: "CB EC Zap", especialidad: "SB", apellidoNombre: "LOPEZ, Sabrina Priscila", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 195, grado: "CB EC Ofic", especialidad: "SB", apellidoNombre: "MARTOCCIA, Florencia Agustina", unidad: "Com Dir Int", cargo: "Cu Grl" },
  { nro: 196, grado: "CB Int", especialidad: "SB", apellidoNombre: "TOLABA, Angel Maximiliano", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 197, grado: "CB Int", especialidad: "SB", apellidoNombre: "FIGUEROA, Agustina Camila Nahir", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 198, grado: "CB Int", especialidad: "SB", apellidoNombre: "FERNANDEZ, Angelica Gisel", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 199, grado: "CB Int", especialidad: "SB", apellidoNombre: "PARDO, Rocio Belèn", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 200, grado: "CB Int", especialidad: "SB", apellidoNombre: "ORTEGA, Gianella Saraì", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 201, grado: "CB Int", especialidad: "SB", apellidoNombre: "ORELLANA, Camila Rita Milagros", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 202, grado: "CB Int", especialidad: "SB", apellidoNombre: "ACOSTA, Rocio Alejandra", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 203, grado: "CB Int", especialidad: "SB", apellidoNombre: "HERRERA, Hernan Facundo", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 204, grado: "CB Int", especialidad: "SB", apellidoNombre: "GONZALEZ, FRANCO MOHAMED", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 205, grado: "CB Int", especialidad: "SB", apellidoNombre: "PEREIRA, Ludmila Eloina", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 206, grado: "CB Int", especialidad: "SB", apellidoNombre: "MARTINEZ, Debora Abigail", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 207, grado: "CB Int", especialidad: "SB", apellidoNombre: "ALEGRE, Santiago Ramon", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 208, grado: "CB Int", especialidad: "SB", apellidoNombre: "BURGOS, Florencia Ariana", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 209, grado: "CB Int", especialidad: "SB", apellidoNombre: "MACIEL, Julia Alejandra", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 210, grado: "CB Int", especialidad: "SB", apellidoNombre: "SUAREZ, Lourdes Ayelen", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 211, grado: "CB Int", especialidad: "SB", apellidoNombre: "CACERES, Andres Aladino", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 212, grado: "CB Int", especialidad: "SB", apellidoNombre: "MOYANO, Leandro Ariel", unidad: "Dir Int - PP", cargo: "Practica" },
  { nro: 213, grado: "VP", especialidad: "SV", apellidoNombre: "MORALES MATIAS MARTIN", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 214, grado: "VP", especialidad: "SV", apellidoNombre: "MENDEZ, ARACELI MAGALI", unidad: "Dir Int", cargo: "Dpto Adq" },
  { nro: 215, grado: "VP", especialidad: "SV", apellidoNombre: "NAPOLITAN SABRINA ANTONELLA", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 216, grado: "VP", especialidad: "SV", apellidoNombre: "GIGENA , LUCILA ANAHI", unidad: "Dir Int", cargo: "Direccion" },
  { nro: 217, grado: "VP", especialidad: "SV", apellidoNombre: "TKACHUK , JUAN EMANUEL", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 218, grado: "VP", especialidad: "SV", apellidoNombre: "RETAMOZO, VANINA", unidad: "B Int 601", cargo: "Jefatura" },
  { nro: 219, grado: "VP", especialidad: "SV", apellidoNombre: "OROZCO, NICOLE ABIGAIL", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 220, grado: "VP", especialidad: "SV", apellidoNombre: "QUIÑONES, LUIS RUBEN MARTIN", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 221, grado: "VP", especialidad: "SV", apellidoNombre: "LOPEZ, MELINA SOLEDAD", unidad: "B Int 601", cargo: "Jefatura" },
  { nro: 222, grado: "VP", especialidad: "SV", apellidoNombre: "MULLER, ENZO NAHUEL", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 223, grado: "VP", especialidad: "SV", apellidoNombre: "GUARIPA , TITO", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 224, grado: "VP", especialidad: "SV", apellidoNombre: "AISAMA , JOSE FERNANDO EXEQUIEL", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 225, grado: "VP", especialidad: "SV", apellidoNombre: "LUNA , JENIFER MARIELA", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 226, grado: "VP", especialidad: "SV", apellidoNombre: "SEVILLA FRIAS, DYLAN LAUTARO JOSE", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 227, grado: "VP", especialidad: "SV", apellidoNombre: "MIÑO , SILVINA NOELI", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 228, grado: "VP", especialidad: "SV", apellidoNombre: "GARCIA, EZEQUIEL", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 229, grado: "VP", especialidad: "SV", apellidoNombre: "CARDOZO , MARCO IVAN", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 230, grado: "VP", especialidad: "SV", apellidoNombre: "CORONEL , AGUSTIN", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 231, grado: "VP", especialidad: "SV", apellidoNombre: "ESPINDOLA, CESIA DEBORA", unidad: "B Int 601", cargo: "Cdo Ser" },
  { nro: 232, grado: "VP", especialidad: "SV", apellidoNombre: "ACSAMA , FERNANDO EMMANUEL", unidad: "B Int 601", cargo: "Cas Subof" },
  { nro: 233, grado: "VP", especialidad: "SV", apellidoNombre: "PEDROZO, SANTIAGO EZEQUIEL", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 234, grado: "VP", especialidad: "SV", apellidoNombre: "SANCHEZ, FACUNDO NAZARENO", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 235, grado: "VP", especialidad: "SV", apellidoNombre: "RUEDA, PABLO YOEL", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 236, grado: "VP", especialidad: "SV", apellidoNombre: "VILLALBA, LUCIA GISEL", unidad: "B Int 601", cargo: "Cdo Ser" },
  { nro: 237, grado: "VP", especialidad: "SV", apellidoNombre: "QUISPE VARGAS, RAFAEL FRANCO", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 238, grado: "VP", especialidad: "SV", apellidoNombre: "RAMOS CHOQUE , GUSTAVO NAHUEL", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 239, grado: "VP", especialidad: "SV", apellidoNombre: "ALBORNOZ, ROCIO ABIGAIL", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 240, grado: "VP", especialidad: "SV", apellidoNombre: "GONZALEZ, LOURDES LUJAN", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 241, grado: "VP", especialidad: "SV", apellidoNombre: "CHURQUINA, MAGALI DE LOS ANGELES", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 242, grado: "VP", especialidad: "SV", apellidoNombre: "ACUÑA ESCOBAR, SANTIAGO RODRIGO", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 243, grado: "VP", especialidad: "SV", apellidoNombre: "AYALA, CLARA BEATRIZ", unidad: "Sas Mil Cen", cargo: "DIV CEN" },
  { nro: 244, grado: "VP", especialidad: "SV", apellidoNombre: "ZAPANA,  CECILIA MARA ABIGAIL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 245, grado: "VP", especialidad: "SV", apellidoNombre: "FERNANDEZ , ANTONIA MARIA LUJAN", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 246, grado: "VP", especialidad: "SV", apellidoNombre: "CARTAGENA , ALEXIS FRANCO", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 247, grado: "VP", especialidad: "SV", apellidoNombre: "RUEDA, ROCIO NAHIR DE LOS ANGELE", unidad: "Sas Mil Cen", cargo: "DIV CEN" },
  { nro: 248, grado: "VP", especialidad: "SV", apellidoNombre: "GARCETE  RIOS, JOSE MANUEL", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 249, grado: "VP", especialidad: "SV", apellidoNombre: "REPETTO  , GONZALO GABRIEL", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 250, grado: "VP", especialidad: "SV", apellidoNombre: "ORELLANA, CAMILA ISABEL", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 251, grado: "VP", especialidad: "SV", apellidoNombre: "MARASTONI, SERGIO MANUEL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 252, grado: "VP", especialidad: "SV", apellidoNombre: "SANCHEZ, DEBORA NOEMI", unidad: "Dir Int comisión", cargo: "San" },
  { nro: 253, grado: "VP", especialidad: "SV", apellidoNombre: "IRIARTE, ANDREA REBECA YAEL", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 254, grado: "VP", especialidad: "SV", apellidoNombre: "MORALES  , NAHUEL ELIAS", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 255, grado: "VP", especialidad: "SV", apellidoNombre: "RODRIGUEZ , OSCAR DANIEL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 256, grado: "VP", especialidad: "SV", apellidoNombre: "PANIAGUA  , MARIA MELISA", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 257, grado: "VP", especialidad: "SV", apellidoNombre: "GONZALEZ , LEONARDO ROBERTO", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 258, grado: "VP", especialidad: "SV", apellidoNombre: "SANCHEZ  , SABRINA ISABEL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 259, grado: "VS", especialidad: "SV", apellidoNombre: "DELLA ROCCA, BRENDA LUCIA", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 260, grado: "VS", especialidad: "SV", apellidoNombre: "ALDERETE, ALEJO LAUTARO", unidad: "B Int 601", cargo: "Sec Ars" },
  { nro: 261, grado: "VS", especialidad: "SV", apellidoNombre: "PAZ, FACUNDO LEONEL", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 262, grado: "VS", especialidad: "SV", apellidoNombre: "CATAN, CAMILA AGUSTINA", unidad: "B Int 601", cargo: "Cas Subof" },
  { nro: 263, grado: "VS", especialidad: "SV", apellidoNombre: "IGNACIO, MILAGROS CAMILA", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 264, grado: "VS", especialidad: "SV", apellidoNombre: "OJEDA, LUIS FERNANDO", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 265, grado: "VS", especialidad: "SV", apellidoNombre: "SOSA  , SILVIA MABEL", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 266, grado: "VS", especialidad: "SV", apellidoNombre: "OVIEDO, SHARON CRISTAL", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 267, grado: "VS", especialidad: "SV", apellidoNombre: "RUBERTI, ALEJANDRO URIEL", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 268, grado: "VS", especialidad: "SV", apellidoNombre: "IANCARELLI, AGUSTIN MATIAS", unidad: "B Int 601", cargo: "COL" },
  { nro: 269, grado: "VS", especialidad: "SV", apellidoNombre: "FLORES, AILIN JENNIFER", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 270, grado: "VS", especialidad: "SV", apellidoNombre: "AGUIRRE, ROMINA", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 271, grado: "VS", especialidad: "SV", apellidoNombre: "AGUERO MIÑO, MILAGROS SOLEDAD", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 272, grado: "VS", especialidad: "SV", apellidoNombre: "FRIAS, FLORENCIA MELINA", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 273, grado: "VS", especialidad: "SV", apellidoNombre: "AYALA , CAMILA LUJAN", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 274, grado: "VS", especialidad: "SV", apellidoNombre: "CEJAS, LAURA MAUREN", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 275, grado: "VS", especialidad: "SV", apellidoNombre: "SANGARA MEZA, BARBARA", unidad: "B Int 601", cargo: "Cas Subof" },
  { nro: 276, grado: "VS", especialidad: "SV", apellidoNombre: "CASTAÑARES , LUCAS AGUSTIN", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 277, grado: "VS", especialidad: "SV", apellidoNombre: "GIL, TAMARA SOLEDAD", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 278, grado: "VS", especialidad: "SV", apellidoNombre: "SOPLAN, LOURDES NICOL ABIGAIL", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 279, grado: "VS", especialidad: "SV", apellidoNombre: "GUTIERREZ, YAMILA ALEJANDRA", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 280, grado: "VS", especialidad: "SV", apellidoNombre: "CRUZ, ZOE LUDMILA", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 281, grado: "VS", especialidad: "SV", apellidoNombre: "FERNANDEZ, BRAIAN MATIAS", unidad: "B Int 601", cargo: "" },
  { nro: 282, grado: "VS", especialidad: "SV", apellidoNombre: "FRANCO, BRISA PRISCILA CANDELA", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 283, grado: "VS", especialidad: "SV", apellidoNombre: "CANO PERRONE, CAMILA NAZARENA", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 284, grado: "VS", especialidad: "SV", apellidoNombre: "MARTINEZ, SOL AYELEN", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 285, grado: "VS", especialidad: "SV", apellidoNombre: "SANTILLAN, MARIANA AYLEN", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 286, grado: "VS", especialidad: "SV", apellidoNombre: "MARTINEZ, ULISES", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 287, grado: "VS", especialidad: "SV", apellidoNombre: "VELAZQUEZ ACOSTA, KATHERINE", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 288, grado: "VS", especialidad: "SV", apellidoNombre: "SANTA CRUZ , EDITH GABRIELA", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 289, grado: "VS", especialidad: "SV", apellidoNombre: "SEGOVIA, ORIANA AYELEN", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 290, grado: "VS", especialidad: "SV", apellidoNombre: "SORIANO , MICAELA JAEL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 291, grado: "VS", especialidad: "SV", apellidoNombre: "RODRIGUEZ, MIRTA GRISELDA", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 292, grado: "VS", especialidad: "SV", apellidoNombre: "GUTIERREZ, RODRIGO EZEQUIEL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 293, grado: "VS", especialidad: "SV", apellidoNombre: "ALBORNOZ  , ABRIL ABIGAIL", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 294, grado: "VS", especialidad: "SV", apellidoNombre: "OVELAR, DIAMELA FERNANDA", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 295, grado: "VS", especialidad: "SV", apellidoNombre: "RIOS  , CRISTIAN GONZALO", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 296, grado: "VS", especialidad: "SV", apellidoNombre: "DAVILA  , MARIANELLA BELEN", unidad: "Sas Mil Cen", cargo: "Jefatura" },
  { nro: 297, grado: "VS", especialidad: "SV", apellidoNombre: "GUTIERREZ, NICOLAS SEBASTIAN", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 298, grado: "VS", especialidad: "SV", apellidoNombre: "CASERES , THIAGO URIEL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 299, grado: "VS", especialidad: "SV", apellidoNombre: "BURGOS  , CARLA AGUSTINA", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 300, grado: "VS", especialidad: "SV", apellidoNombre: "SERRANO FRISOLI, SOFIA ISABEL", unidad: "Dir Int", cargo: "San" },
  { nro: 301, grado: "VS", especialidad: "SV", apellidoNombre: "SERRANO, CANDELA MAGALI", unidad: "Dir Int", cargo: "San" },
  { nro: 302, grado: "VS", especialidad: "SV", apellidoNombre: "DUPLESSY , ELIAS AARON", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 303, grado: "VS", especialidad: "SV", apellidoNombre: "AGUADO, JUAN MARTIN", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 304, grado: "SV EC", especialidad: "SV", apellidoNombre: "GOMEZ VILCA, CAMILA BELEN", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 305, grado: "SV EC", especialidad: "SV", apellidoNombre: "GIMENEZ , NADIA CECILIA", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 306, grado: "SV EC", especialidad: "SV", apellidoNombre: "AGUIRRE, SANTIAGO NAHUEL", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 307, grado: "SV EC", especialidad: "SV", apellidoNombre: "CRUZ, LARA NICOLE", unidad: "B Int 601", cargo: "Cas Of" },
  { nro: 308, grado: "SV EC", especialidad: "SV", apellidoNombre: "VILLCA FLORES, EMILCE TATIANA", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 309, grado: "SV EC", especialidad: "SV", apellidoNombre: "MANCILLA, CAMILA", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 310, grado: "SV EC", especialidad: "SV", apellidoNombre: "CRUZ, GONZALO RUBEN", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 311, grado: "SV EC", especialidad: "SV", apellidoNombre: "RUIZ, JUAN PABLO", unidad: "B Int 601", cargo: "NIB" },
  { nro: 312, grado: "SV EC", especialidad: "SV", apellidoNombre: "BERTOLINI, ELISABET ALEJANDRA", unidad: "B Int 601", cargo: "Taller Bda" },
  { nro: 313, grado: "SV EC", especialidad: "SV", apellidoNombre: "ALMIRON, SONIA CELESTE", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 314, grado: "SV EC", especialidad: "SV", apellidoNombre: "ALVAREZ, JENIFFER ISABEL", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 315, grado: "SV EC", especialidad: "SV", apellidoNombre: "YEGROS, DENISSE IVANA PRISCILA", unidad: "B Int 601", cargo: "Cas Subof" },
  { nro: 316, grado: "SV EC", especialidad: "SV", apellidoNombre: "CID, ANTONIO BALDUVINO", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 317, grado: "SV EC", especialidad: "SV", apellidoNombre: "ALVAREZ REY, IGNACIO LEÓN", unidad: "B Int 601", cargo: "Sec Ars" },
  { nro: 318, grado: "SV EC", especialidad: "SV", apellidoNombre: "PAREDES BENITEZ, LOURDES", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 319, grado: "SV EC", especialidad: "SV", apellidoNombre: "ORTIZ, LUDMILA PRISCILA", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 320, grado: "SV EC", especialidad: "SV", apellidoNombre: "LEITES , HAILEEN ANTONELLA", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 321, grado: "SV EC", especialidad: "SV", apellidoNombre: "SENA, IARA MICOL", unidad: "B Int 601", cargo: "Ca AB" },
  { nro: 322, grado: "SV EC", especialidad: "SV", apellidoNombre: "GONZALEZ , MICAELA ARIADNA", unidad: "B Int 601", cargo: "Sec Int" },
  { nro: 323, grado: "SV EC", especialidad: "SV", apellidoNombre: "VERA, ELIANA NAZARENA", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 324, grado: "SV EC", especialidad: "SV", apellidoNombre: "ESPINDOLA, JEMIMA", unidad: "B Int 601", cargo: "NIB" },
  { nro: 325, grado: "SV EC", especialidad: "SV", apellidoNombre: "CAPURRO , NESTOR CARLOS", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 326, grado: "SV EC", especialidad: "SV", apellidoNombre: "SAUCEDO, KEVIN RAMON", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 327, grado: "SV EC", especialidad: "SV", apellidoNombre: "DURE, CELINA MARIA", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 328, grado: "SV EC", especialidad: "SV", apellidoNombre: "RUIZ JUAREZ, DYLAN ALEXANDER", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 329, grado: "SV EC", especialidad: "SV", apellidoNombre: "GONZALEZ, YAMILA NADIN", unidad: "B Int 601", cargo: "Ca Ab" },
  { nro: 330, grado: "SV EC", especialidad: "SV", apellidoNombre: "ESQUIVEL, LUCIANA BELEN", unidad: "B Int 601", cargo: "NIB" },
  { nro: 331, grado: "SV EC", especialidad: "SV", apellidoNombre: "IBARRA, MATIAS", unidad: "B Int 601", cargo: "NIB" },
  { nro: 332, grado: "SV EC", especialidad: "SV", apellidoNombre: "VILLAROEL, IVAN ALEXANDER", unidad: "B Int 601", cargo: "NIB" },
  { nro: 333, grado: "SV EC", especialidad: "SV", apellidoNombre: "OLGUIN, OMAR ROMERO", unidad: "B Int 601", cargo: "NIB" },
  { nro: 334, grado: "SV EC", especialidad: "SV", apellidoNombre: "SORIA, LAUTARO MICHEL", unidad: "B Int 601", cargo: "COL" },
  { nro: 335, grado: "SV EC", especialidad: "SV", apellidoNombre: "BRITOS, BELÉN ANTONELLA", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 336, grado: "SV EC", especialidad: "SV", apellidoNombre: "SANCHEZ, BARBARA SABRINA", unidad: "Dir Int", cargo: "DAF Dir Int" },
  { nro: 337, grado: "SV EC", especialidad: "SV", apellidoNombre: "GARCIA, LEONARDO GABRIEL", unidad: "Dir Int", cargo: "Direccion" },
  { nro: 338, grado: "SV EC", especialidad: "SV", apellidoNombre: "ROGULOTTO, AGUSTIN", unidad: "Dir Int", cargo: "San" },
  { nro: 339, grado: "SV EC", especialidad: "SV", apellidoNombre: "VALLEJOS, LAUTARO ALEJANDRO", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 340, grado: "SV EC", especialidad: "SV", apellidoNombre: "QUIROGA BENITEZ, SANTIAGO", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 341, grado: "SV EC", especialidad: "SV", apellidoNombre: "AVILA MORENO, EVELYN MICAELA", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 342, grado: "SV EC", especialidad: "SV", apellidoNombre: "DE PABLO, ADRIANA VALENTINA", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 343, grado: "SV EC", especialidad: "SV", apellidoNombre: "QUIROGA VIDAL, VALENTIN", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 344, grado: "SV EC", especialidad: "SV", apellidoNombre: "RODRIGUEZ GALARZA, SANTIAGO", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 345, grado: "SV EC", especialidad: "SV", apellidoNombre: "DEL VALLE ARGUELLO, MARIA", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 346, grado: "SV EC", especialidad: "SV", apellidoNombre: "TATSCH , NAHIARA BELÉN", unidad: "Dir Int", cargo: "Cas Of" },
  { nro: 347, grado: "SV EC", especialidad: "SV", apellidoNombre: "SUAREZ, TOBIAS GABRIEL", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 348, grado: "SV EC", especialidad: "SV", apellidoNombre: "ALARCON, LUCA MARTIN", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 349, grado: "SV EC", especialidad: "SV", apellidoNombre: "FERNANDEZ SEGOVIA, MELANIE", unidad: "Dir Int", cargo: "Dpto Insp" },
  { nro: 350, grado: "SV EC", especialidad: "SV", apellidoNombre: "GRANERO, JAVIER ALBERTO", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 351, grado: "SV EC", especialidad: "SV", apellidoNombre: "VAZQUEZ, CELESTE AYELEN", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 352, grado: "SV EC", especialidad: "SV", apellidoNombre: "TOLOZA, PRISCILA MILAGROS", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 353, grado: "SV EC", especialidad: "SV", apellidoNombre: "SEGOVIA, LAUTARO EMIR", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 354, grado: "SV EC", especialidad: "SV", apellidoNombre: "CAÑETE, PRISCILA MARIBEL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 355, grado: "SV EC", especialidad: "SV", apellidoNombre: "SENES, CHRISTIAN LAUTARO", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 356, grado: "SV EC", especialidad: "SV", apellidoNombre: "SANCHEZ, MAILEN ABIGAIL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 357, grado: "SV EC", especialidad: "SV", apellidoNombre: "BARBOSA BARRIOS, KIARA AILEN", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 358, grado: "SV EC", especialidad: "SV", apellidoNombre: "CABRERA, JAZMIN", unidad: "Sas Mil Cen", cargo: "DAF Sas Mil" },
  { nro: 359, grado: "SV EC", especialidad: "SV", apellidoNombre: "FONTELA , BRIAN EMILIANO", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 360, grado: "SV EC", especialidad: "SV", apellidoNombre: "MAMANI, ALEJANDRO ARIEL", unidad: "Sas Mil Cen", cargo: "DPTO PROD" },
  { nro: 361, grado: "V - 6", especialidad: "AC", apellidoNombre: "VALDES, ESTELA MARIS", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 362, grado: "V - 6", especialidad: "AC", apellidoNombre: "CENZANO, CLAUDIO ALEJANDRO", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 363, grado: "VI - 6", especialidad: "AC", apellidoNombre: "MEZA, NICOLAS MAURO MANUEL", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 364, grado: "VI - 6", especialidad: "AC", apellidoNombre: "RAMOS, JORGE", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 365, grado: "VI - 6", especialidad: "AC", apellidoNombre: "INTRA, ALBERTO OSCAR", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 366, grado: "VI - 6", especialidad: "AC", apellidoNombre: "GODOY, ABEL ANTONIO", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 367, grado: "VI - 6", especialidad: "AC", apellidoNombre: "SERRANO, JORGE ANTONIO", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 368, grado: "VII - 6", especialidad: "AC", apellidoNombre: "SAGANIAS, ADRIAN ALBERTO", unidad: "B Int 601", cargo: "Sec Calzado" },
  { nro: 369, grado: "VI - 8", especialidad: "AC", apellidoNombre: "BARRIONUEVO, JOSE JAVIER", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 370, grado: "VI - 8", especialidad: "AC", apellidoNombre: "DOS SANTOS, RAMON EZEQUIEL", unidad: "B Int 601", cargo: "Sec Destinos" },
  { nro: 371, grado: "VII - 8", especialidad: "AC", apellidoNombre: "OLIVERA, GABRIEL ESTEBAN", unidad: "B Int 601", cargo: "Sec Panadería" },
  { nro: 372, grado: "III - 11", especialidad: "AC", apellidoNombre: "DI PRINZIO, VANINA JULIETA", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 373, grado: "IV - 11", especialidad: "AC", apellidoNombre: "LEIVA, ADOLFO", unidad: "B Int 601", cargo: "Cas Of" },
  { nro: 374, grado: "IV - 15", especialidad: "AC", apellidoNombre: "AMARILLA, SILVIA PATRICIA", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 375, grado: "VII - 3", especialidad: "AC", apellidoNombre: "OCAÑO, MARIA VICTORIA", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 376, grado: "III - 4", especialidad: "AC", apellidoNombre: "RODRIGUEZ, MELANIE YASMIN", unidad: "Dir Int", cargo: "Cu Grl" },
  { nro: 377, grado: "VII - 4", especialidad: "AC", apellidoNombre: "RUBERTI, SILVIO GERARDO", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 378, grado: "III - 6", especialidad: "AC", apellidoNombre: "RICCARDI, MARIA FLORENCIA", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 379, grado: "III - 6", especialidad: "AC", apellidoNombre: "FERRERIA, ALEJANDRO GUSTAVO", unidad: "Dir Int", cargo: "Div Com Info" },
  { nro: 380, grado: "VI - 6", especialidad: "AC", apellidoNombre: "INSAURRALDE, MARCELA ALEJANDRA", unidad: "Dir Int", cargo: "Dpto Insp" },
  { nro: 381, grado: "VII - 6", especialidad: "AC", apellidoNombre: "MERLO, CAROLINA ANDREA", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 382, grado: "VII - 6", especialidad: "AC", apellidoNombre: "QUIROGA, GREGORIA", unidad: "Dir Int", cargo: "Dpto Téc" },
  { nro: 383, grado: "II - 8", especialidad: "AC", apellidoNombre: "SANTTO, VERONICA PAULA", unidad: "Dir Int", cargo: "Dpto Insp" },
  { nro: 384, grado: "III - 13", especialidad: "AC", apellidoNombre: "ANDIARENA, ROBERTO OMAR", unidad: "Dir Int", cargo: "Dpto Ab y Mant" },
  { nro: 385, grado: "CAPELLAN AUXILIAR (TT)", especialidad: "AC", apellidoNombre: "ROJAS SANABRIA, EUSEBIO", unidad: "Dir Int", cargo: "PADRE" },
  { nro: 386, grado: "IV - 6", especialidad: "AC", apellidoNombre: "GOMEZ SANCHEZ, EUSEBIO", unidad: "Sas Mil Cen", cargo: "SUC CABILDO" },
  { nro: 387, grado: "V - 6", especialidad: "AC", apellidoNombre: "CASALS, DEBORA", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 388, grado: "V - 6", especialidad: "AC", apellidoNombre: "FERNANDEZ, MARIEL ELIZABETH", unidad: "Sas Mil Cen", cargo: "CRE" },
  { nro: 389, grado: "V - 6", especialidad: "AC", apellidoNombre: "ALIAGA ORDINOLA, EDILBERTO", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 390, grado: "V - 6", especialidad: "AC", apellidoNombre: "MADERA, ANA CATALINA", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 391, grado: "V - 7", especialidad: "AC", apellidoNombre: "MUÑOZ, CECILIA CAROLINA", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 392, grado: "V - 8", especialidad: "AC", apellidoNombre: "CEBALLOS, MARISA", unidad: "Sas Mil Cen", cargo: "SUC CABILDO" },
  { nro: 393, grado: "V - 9", especialidad: "AC", apellidoNombre: "DURAN, GABRIELA LEONOR", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 394, grado: "IV - 12", especialidad: "AC", apellidoNombre: "AGUIRRE, RICARDO GUSTAVO", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 395, grado: "III - 14", especialidad: "AC", apellidoNombre: "STIGLIANO, CRISTIAN JAVIER", unidad: "Sas Mil Cen", cargo: "DPTO COMER" },
  { nro: 396, grado: "V - 8", especialidad: "AC", apellidoNombre: "SUAREZ, MARIA GABRIELA", unidad: "Sas Mil Suc CORDOBA", cargo: "DPTO COMER" },
  { nro: 397, grado: "V - 8", especialidad: "AC", apellidoNombre: "BORDALLO, ROXANA ANABEL", unidad: "Sas Mil Suc MZA", cargo: "DPTO COMER" },
  { nro: 398, grado: "IV - 13", especialidad: "AC", apellidoNombre: "MORON, ARMANDO ENRIQUE", unidad: "Sas Mil Suc MENDOZA", cargo: "DPTO COMER" },
];
